(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type size =
  [ `_256x256
    [@printer fun fmt _ -> Format.pp_print_string fmt "256x256"]
    [@name "256x256"]
  | `_512x512
    [@printer fun fmt _ -> Format.pp_print_string fmt "512x512"]
    [@name "512x512"]
  | `_1024x1024
    [@printer fun fmt _ -> Format.pp_print_string fmt "1024x1024"]
    [@name "1024x1024"] ]
[@@deriving yojson, show { with_path = false }]

let size_of_yojson json = size_of_yojson (`List [ json ])

let size_to_yojson e =
  match size_to_yojson e with `List [ json ] -> json | json -> json

type role =
  [ `System
    [@printer fun fmt _ -> Format.pp_print_string fmt "system"]
    [@name "system"]
  | `User
    [@printer fun fmt _ -> Format.pp_print_string fmt "user"]
    [@name "user"]
  | `Assistant
    [@printer fun fmt _ -> Format.pp_print_string fmt "assistant"]
    [@name "assistant"] ]
[@@deriving yojson, show { with_path = false }]

let role_of_yojson json = role_of_yojson (`List [ json ])

let role_to_yojson e =
  match role_to_yojson e with `List [ json ] -> json | json -> json

type response_format =
  [ `Url [@printer fun fmt _ -> Format.pp_print_string fmt "url"] [@name "url"]
  | `B64_json
    [@printer fun fmt _ -> Format.pp_print_string fmt "b64_json"]
    [@name "b64_json"] ]
[@@deriving yojson, show { with_path = false }]

let response_format_of_yojson json = response_format_of_yojson (`List [ json ])

let response_format_to_yojson e =
  match response_format_to_yojson e with `List [ json ] -> json | json -> json
