(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* The role of the author of this message. *)
    role: Enums.role;
    (* The contents of the message *)
    content: string;
} [@@deriving yojson { strict = false }, show ];;

let create (role : Enums.role) (content : string) : t = {
    role = role;
    content = content;
}

