(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  (* Query to be classified. *)
  query : string;
  (* A list of examples with labels, in the following format:  `[[\''The movie is so interesting.\'', \''Positive\''], [\''It is quite boring.\'', \''Negative\''], ...]`  All the label strings will be normalized to be capitalized.  You should specify either `examples` or `file`, but not both.  *)
  examples : string list list;
  (* The ID of the uploaded file that contains training examples. See [upload file](/docs/api-reference/files/upload) for how to upload a file of the desired format and purpose.  You should specify either `examples` or `file`, but not both.  *)
  file : string option; [@default None]
  (* The set of categories being classified. If not specified, candidate labels will be automatically collected from the examples you provide. All the label strings will be normalized to be capitalized. *)
  labels : string list;
  (* What sampling temperature to use, between 0 and 2. Higher values like 0.8 will make the output more random, while lower values like 0.2 will make it more focused and deterministic. *)
  temperature : float option; [@default None]
  (* The maximum number of examples to be ranked by [Search](/docs/api-reference/searches/create) when using `file`. Setting it to a higher value leads to improved accuracy but with increased latency and cost. *)
  max_examples : int32 option; [@default None]
}
[@@deriving yojson { strict = false }, show, make]
