(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    _object: string option [@default None] [@key "object"];
    model: string option [@default None];
    search_model: string option [@default None];
    completion: string option [@default None];
    label: string option [@default None];
    selected_examples: Create_classification_response_selected_examples.t list;
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    _object = None;
    model = None;
    search_model = None;
    completion = None;
    label = None;
    selected_examples = [];
}

