(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    text: string option [@default None];
    index: int32 option [@default None];
    logprobs: Create_completion_response_logprobs.t option [@default None];
    finish_reason: string option [@default None];
} [@@deriving yojson { strict = false }, show, make ];;
