(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    id: string;
    _object: string [@key "object"];
    created: int32;
    model: string;
    choices: Create_chat_completion_response_choices.t list;
    usage: Create_completion_response_usage.t option [@default None];
} [@@deriving yojson { strict = false }, show, make ];;
