(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* The image to edit. Must be a valid PNG file, less than 4MB, and square. If mask is not provided, image must have transparency, which will be used as the mask. *)
    image: string;
    (* An additional image whose fully transparent areas (e.g. where alpha is zero) indicate where `image` should be edited. Must be a valid PNG file, less than 4MB, and have the same dimensions as `image`. *)
    mask: string option [@default None];
    (* A text description of the desired image(s). The maximum length is 1000 characters. *)
    prompt: string;
} [@@deriving yojson { strict = false }, show, make ];;
