(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    _object: string option [@default None] [@key "object"];
    model: string option [@default None];
    data: Create_search_response_data.t list;
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    _object = None;
    model = None;
    data = [];
}

