(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    (* The image to use as the basis for the variation(s). Must be a valid PNG file, less than 4MB, and square. *)
    image: string;
} [@@deriving yojson { strict = false }, show, make ];;
