(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    hate: float;
    hate_threatening: float;
    self_harm: float;
    sexual: float;
    sexual_minors: float;
    violence: float;
    violence_graphic: float;
} [@@deriving yojson { strict = false }, show ];;

let create (hate : float) (hate_threatening : float) (self_harm : float) (sexual : float) (sexual_minors : float) (violence : float) (violence_graphic : float) : t = {
    hate = hate;
    hate_threatening = hate_threatening;
    self_harm = self_harm;
    sexual = sexual;
    sexual_minors = sexual_minors;
    violence = violence;
    violence_graphic = violence_graphic;
}

