(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    hate: bool;
    hate_threatening: bool;
    self_harm: bool;
    sexual: bool;
    sexual_minors: bool;
    violence: bool;
    violence_graphic: bool;
} [@@deriving yojson { strict = false }, show, make ];;
