(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    _object: string option [@default None];
    document: int32 option [@default None];
    score: float option [@default None];
} [@@deriving yojson { strict = false }, show ];;

let create () : t = {
    _object = None;
    document = None;
    score = None;
}

