(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
  hate : float;
  hate_threatening : float;
  self_harm : float;
  sexual : float;
  sexual_minors : float;
  violence : float;
  violence_graphic : float;
}
[@@deriving yojson { strict = false }, show, make]
