(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    text: string;
} [@@deriving yojson { strict = false }, show ];;

let create (text : string) : t = {
    text = text;
}

