(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    hate: bool;
    hate_threatening: bool;
    self_harm: bool;
    sexual: bool;
    sexual_minors: bool;
    violence: bool;
    violence_graphic: bool;
} [@@deriving yojson { strict = false }, show ];;

let create (hate : bool) (hate_threatening : bool) (self_harm : bool) (sexual : bool) (sexual_minors : bool) (violence : bool) (violence_graphic : bool) : t = {
    hate = hate;
    hate_threatening = hate_threatening;
    self_harm = self_harm;
    sexual = sexual;
    sexual_minors = sexual_minors;
    violence = violence;
    violence_graphic = violence_graphic;
}

