(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    id: string;
    _object: string [@key "object"];
    deleted: bool;
} [@@deriving yojson { strict = false }, show ];;

let create (id : string) (_object : string) (deleted : bool) : t = {
    id = id;
    _object = _object;
    deleted = deleted;
}

