(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    id: string;
    _object: string [@key "object"];
    created: int32 option;
    ready: bool;
} [@@deriving yojson { strict = false }, show ];;

let create (id : string) (_object : string) (created : int32 option) (ready : bool) : t = {
    id = id;
    _object = _object;
    created = created;
    ready = ready;
}

