(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    id: string;
    _object: string [@key "object"];
    created_at: int32;
    updated_at: int32;
    model: string;
    fine_tuned_model: string option;
    organization_id: string;
    status: string;
    hyperparams: Yojson.Safe.t;
    training_files: Open_ai_file.t list;
    validation_files: Open_ai_file.t list;
    result_files: Open_ai_file.t list;
    events: Fine_tune_event.t list;
} [@@deriving yojson { strict = false }, show ];;

let create (id : string) (_object : string) (created_at : int32) (updated_at : int32) (model : string) (fine_tuned_model : string option) (organization_id : string) (status : string) (hyperparams : Yojson.Safe.t) (training_files : Open_ai_file.t list) (validation_files : Open_ai_file.t list) (result_files : Open_ai_file.t list) : t = {
    id = id;
    _object = _object;
    created_at = created_at;
    updated_at = updated_at;
    model = model;
    fine_tuned_model = fine_tuned_model;
    organization_id = organization_id;
    status = status;
    hyperparams = hyperparams;
    training_files = training_files;
    validation_files = validation_files;
    result_files = result_files;
    events = [];
}

