(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    _object: string [@key "object"];
    created_at: int32;
    level: string;
    message: string;
} [@@deriving yojson { strict = false }, show ];;

let create (_object : string) (created_at : int32) (level : string) (message : string) : t = {
    _object = _object;
    created_at = created_at;
    level = level;
    message = message;
}

