(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    _object: string [@key "object"];
    created_at: int32;
    level: string;
    message: string;
} [@@deriving yojson { strict = false }, show, make ];;
