(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    created: int32;
    data: Images_response_data.t list;
} [@@deriving yojson { strict = false }, show, make ];;
