(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    _object: string [@key "object"];
    data: Open_ai_file.t list;
} [@@deriving yojson { strict = false }, show ];;

let create (_object : string) (data : Open_ai_file.t list) : t = {
    _object = _object;
    data = data;
}

