(*
 * This file has been generated by the OCamlClientCodegen generator for openapi-generator.
 *
 * Generated by: https://openapi-generator.tech
 *
 *)

type t = {
    id: string;
    _object: string;
    created: int32;
    owned_by: string;
} [@@deriving yojson { strict = false }, show ];;

let create (id : string) (_object : string) (created : int32) (owned_by : string) : t = {
    id = id;
    _object = _object;
    created = created;
    owned_by = owned_by;
}

